name: Java CI with Gradle

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Change to back-end directory
        run: cd back-end

      - name: Gradle wrapper setup
        run: ./gradlew wrapper --gradle-version 7.6

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
