name: Java CI with Gradle

on:
  push:
    branches:
      - main  # Ou qualquer outra branch que você queira monitorar
  pull_request:
    branches:
      - main  # Ou qualquer outra branch que você queira monitorar

jobs:
  build:
    runs-on: ubuntu-latest  # Usamos o Ubuntu para o runner do GitHub Actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Faz o checkout do código do repositório

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'  # Define o JDK 24
          distribution: 'adoptium'  # 'adoptium' é uma das distribuições comuns do OpenJDK (se o JDK 24 estiver disponível)

      - name: Change to back-end directory
        run: cd back-end  # Altere para o diretório correto

      - name: Gradle wrapper setup
        run: ./gradlew wrapper --gradle-version 7.6  # Garante que o wrapper do Gradle esteja correto, ajuste a versão se necessário

      - name: Build with Gradle
        run: ./gradlew build  # Executa o build com Gradle, incluindo os testes

      - name: Run tests
        run: ./gradlew test  # Executa os testes
